language: node_js
node_js:
- '6'
script:
- cd server
- npm install
- npm test
env:
  matrix:
  global:
    - TZ=America/New_York
    - secure: oviP+Szg5A/k4pAxjiWFzLSukJoxyH7dXcKwaX2AFZjdi2+Yzd5zr0zuW/p5+2VDfvD3KmdZlg9xeUkwOrZDddsYd1zuCJLBSVjckfrpklYkHsmqdQCqg8dfiv7kkbOKngdCZsWg7ifm5JCJPBAZ4pDiSeM2c/XG/IzMDHpFhwyO8m8GOpGskNk7wEJ7kZuFe2kpdRBc6L6yOCdn0flfrYrt1z8UXMaW4u/TuC/FAF72BIy4KvVFooEmdue4cSHTAbgIGbHMhLCEpSnJQd5wdXwLRytb3w+vgotJ5Pw/pAn/ivLHL5Mse74OMjaSnWBsxywxFt/M4xvEFrzx6Zzvt7mPDRQlad8gDI+BUAJxxmPVnUDiQXvvTeDyvI3m34/K4H4VhWf9LY4jdhYLZW9dHNGYxLFIScnN2+E1TXeOM94GL/+h7KQmfHW04cA+cVdjSdBrwbMKSpzqqEsRjSkG6fxogvcH7L9SF1cWioOmiOaJDOIyZPYvpaKxWvfujHun2Bzu5dZCk2GNYwQIGQzOgFVSVDWxg5rsIupX78jp76mIzDxaTEnZU9m/t1l4F7bGpbcn8g3Vbe2jH3JdxLWc7mtFKaKiK7D1HeehYnRh4wXhfTB73hWm+/44dUaEyip42pN7NYKmFh9kXXezBzDyAe7eAlBVJXTMk7oHoNV/jxM=
