language: node_js

node_js:
  - "6"

script:
  - cd server
  - npm install
  - npm test

env:
  matrix:
    - TZ=America/New_York
    - secure: ARSp8WVxMUMJYMNecG05zyzmFHFMtfvLeZrRa8K6P9q5kfREKVudBC+g8EQonLbq18bHdnpOTXUhHRgh3rOQOZHwyNCIbqN6cmk9/Yyo9F1Oxu2R+f50sAXCCwV9A/ExjLh330eoEw9pQyeLU7nga+VbGLh3rtqWqWafPeiOQBJIvmD8ryjxSPXMawSG0x2eATdZuy5chXRR0Yzma59Dtotl049s2d+3fpYpbqgUAIwYhewsaf8S0tsO2IBbcikkqAh8UTWPf7NmNHOu36Esk9flLf48SVIurrn5HnBdnQjYbAt7GdRvQjqEmjvdQjrLwltwm8W2eiteetIoJLF1AkUuVle/5N7/HW9johvBwVHyOJpBHIcpoDN30ihudWs0y31AjDHSEli+Yr8whGjlqAAIaNKM2dO6oUnDtAyTeb3UAxjTaEeIE7esueDvcgf+HaN/jD0yYR0smlcjcGTg0+PC0NVvEMwaeI4Ctv5m1TWVPFYFezU8MlbnCYGYZW2Ng8xaOJm2iKec3DCvlEtthTHD3BjxFW/xZq8DW/n6a0z8QrdoQ41pEBcHsJFrK5JLYADgqQ2BQVtlbFsQ7mzMaTBmPGOidQDvQISh7eNXCLJeu7zlUsz/mL5DHwVMDb1fGj3eIDtS0sPZV2sS3x4ZFIsMQdjBZrD9Gh9kCDUM6eM=
